import type { NextPage } from "next";
import Head from "next/head";
import { ChangeEvent, useEffect, useState } from "react";
import Banner from "../components/Banner";
import Clients from "../components/Clients";
import CTA from "../components/CTA";
import { Footer } from "../components/Footer";
import Navbar from "../components/Navbar";
import Perks from "../components/Perks";
import Starter from "../components/Starter";
import Stats from "../components/Stats";
import Testimonal from "../components/Testimonal";
import { useRouter } from "next/router";
import Profile from "./profile/Profile";


const Home: NextPage = () => {
  const [token, setToken] = useState(false);

  const router = useRouter()

  useEffect(() =>{
   const user = JSON.parse(localStorage.getItem("userInfo") || 'false')

    if (user) setToken(true)
  },[token])

 

  return (
    <div className="back color h-screen  overflow-x-hidden select-none">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {token ? (
        <Profile />
      ) : (
        <div>
          <Navbar />
          <Banner />
          <Starter />
          <Stats />
          <Perks />
          <Testimonal />
          <Clients />
          <CTA />
          <Footer />
        </div>
      )}
    </div>
  );
};

export default Home;
