import type { NextPage } from "next";
import Head from "next/head";
import { ChangeEvent, useState } from "react";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Perks from "../components/Perks";
import Starter from "../components/Starter";
import Testimonal from "../components/Testimonal";
import SignInForm from "./registration/SignInForm";


const Home: NextPage = () => {


  return (
    <div className="back color h-screen  overflow-x-hidden select-none">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner />
      <Starter />
      <Perks />
      <Testimonal />
      <Footer />
    
    </div>
  );
};

export default Home;
